// Generated by https://quicktype.io

export interface Settings {
  name: string;
  avatar: string;
  bio: string;
  job: string;
  description: string;
  social: Social[];
  contacts: ResumeContact[];
  navigation: Navigation[];
  skills: SettingsSkills;
  portfolio: Portfolio;
  resume: Resume;
  testimonials: Testimonials;
  contact: PurpleContact;
  businessCard: BusinessCard;
}

export interface BusinessCard {
  header: Header;
  contacts: BusinessCardContact[];
  footer: Footer;
}

export interface BusinessCardContact {
  key: string;
  value: string;
  link: string;
}

export interface Footer {
  company: string;
  address: string;
  website: string;
  alias: string;
}

export interface Header {
  name: string;
  profession: string;
  logo: string;
}

export interface PurpleContact {
  title: string;
  subtitle: string;
}

export interface ResumeContact {
  value: string;
  link: string;
  icon: string;
}

export interface Navigation {
  path: string;
  icon: string;
  label: string;
  component: string;
}

export interface Portfolio {
  title: string;
  subtitle: string;
  projects: Project[];
}

export interface Project {
  title: string;
  subtitle: string;
  client: string;
  website?: string;
  slug: string;
  screenshots: string[];
  technologies: Technology[];
  description: string;
}

export interface Technology {
  name: Name;
  values: string[];
}

export enum Name {
  Backend = "Backend",
  CMS = "CMS",
  Frontend = "Frontend",
}

export interface Resume {
  title: string;
  name: string;
  job: string;
  contacts: ResumeContact[];
  avatar: string;
  bio: string;
  works: Works;
  skills: ResumeSkills;
  education: Education;
  languages: Languages;
  interests: Interests;
  projects: Projects;
}

export interface Education {
  title: string;
  items: EducationItem[];
}

export interface EducationItem {
  school: string;
  title: string;
  icon: string;
  from: number;
  to: number;
}

export interface Interests {
  title: string;
  items: InterestsItem[];
}

export interface InterestsItem {
  value: string;
}

export interface Languages {
  title: string;
  items: LanguagesItem[];
}

export interface LanguagesItem {
  language: string;
  level: string;
  icon: string;
}

export interface Projects {
  title: string;
  items: ProjectsItem[];
}

export interface ProjectsItem {
  title: string;
  icon: string;
  subtitle: string;
}

export interface ResumeSkills {
  title: string;
  items: SkillsItem[];
}

export interface SkillsItem {
  topic: string;
  list: ItemList[];
}

export interface ItemList {
  value: string;
  icon?: PurpleIcon;
}

export interface PurpleIcon {
  name: string;
  color: string;
}

export interface Works {
  title: string;
  items: WorksItem[];
}

export interface WorksItem {
  title: string;
  company: string;
  link?: string;
  place?: string;
  icon: string;
  from: string;
  to: string;
  description?: string;
}

export interface SettingsSkills {
  title: string;
  subtitle: string;
  list: SkillsList[];
}

export interface SkillsList {
  name: string;
  icons: IconElement[];
}

export interface IconElement {
  icon: string;
  color: string;
}

export interface Social {
  name: string;
  link: string;
  color: string;
}

export interface Testimonials {
  hidden: boolean;
  title: string;
  items: TestimonialsItem[];
}

export interface TestimonialsItem {
  description: string;
  avatar: string;
  name: string;
  job: string;
}
